version: 2.1

defaults:
  &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:19.0

# We use two install commands to allow the npm install operation to occur with a prefix.
commands:
  install1:
    steps:
      - restore_cache:
      # https://circleci.com/docs/caching/#source-caching if the repo grows too big, replace source-cache with dependency-cache, git clone can be faster than restore_cache.
          keys:
            - &source-cache source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - checkout
  install2:
    steps:
      - save_cache:
          key: *source-cache
          paths:
            - ".git"

jobs:
  musicbox:
    <<: *defaults
    steps:
      - install1
      - run: npm install --prefix musicbox
      - install2
      - run: node musicbox/musicbox.js
    resource_class: small

  osubox:
    <<: *defaults
    steps:
      - install1
      - run: npm install --prefix osubox
      - install2
      - run: node osubox/osubox.js
    resource_class: small

workflows:

# Test will deploy on every push to master.
  test:
    jobs:
      - musicbox
      - osubox

# Poll will deploy on a schedule.
  musicbox_poll:
    triggers:
      - schedule:
          # Run every hour.
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - musicbox
  
  osubox_poll:
    triggers:
      - schedule:
          # Run at midnight.
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - osubox