version: 2.1

defaults:
  &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:19.0

commands:
  install1:
    steps:
      - restore_cache:
          keys:
            - &source-cache source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
            # - node-v1-musicbox-{{ checksum "package.json" }}
            # - node-v1-osubox-{{ checksum "package.json" }}
      - checkout
  install2:
    steps:
      - save_cache:
          key: *source-cache
          paths:
            - ".git"

  # install-osubox:
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           - dependency-cache-{{ checksum "osubox/package.json" }}
  #           - dependency-cache-
  #     - run: npm install --prefix osubox
  #     - save_cache:
  #         key: dependency-cache-{{ checksum "osubox/package.json" }}
  #         paths:
  #           - osubox/node_modules

jobs:
  musicbox:
    <<: *defaults
    steps:
      - install1
      - run: npm install --prefix musicbox
      - install2
      - run: node musicbox/musicbox.js
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    # resource_class: large
    resource_class: small

  osubox:
    <<: *defaults
    steps:
      - install1
      - run: npm install --prefix osubox
      - install2
      - run: node osubox/osubox.js
    resource_class: small

workflows:

# Test will deploy on every push to master.
  test:
    jobs:
      - musicbox
      - osubox

# Poll will deploy on a schedule.
  musicbox_poll:
    triggers:
      - schedule:
          # Run every hour.
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - musicbox
  
  osubox_poll:
    triggers:
      - schedule:
          # Run at midnight.
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - osubox